/**
 * Textes français des défis du terminal (traduction HESTIM des défis de Terminal Quest, MIT).
 * L'anglais reste dans moteur.js et sert de repli. Les commandes et leurs sorties restent
 * telles qu'un vrai shell Linux les affiche (en anglais).
 *
 * Par défi : niveau (nom du niveau), titre, explication, objectif, indices (3, du plus vague à
 * la réponse), echec (message quand l'objectif n'est pas atteint).
 */

export const INDICES_PAR_DEFAUT_FR = [
    "Quelle commande correspond à cet objectif ?",
    "Si le nom vous échappe, tapez help pour la liste ou man <commande> pour l'aide d'une commande.",
    "Essayez la forme la plus simple et lisez la réponse du terminal.",
];

export const DEFIS_FR = {
    "orientation-01": {
        niveau: "Où suis-je ?",
        titre: "Prendre ses repères",
        explication: "Avant de toucher à quoi que ce soit, repérez-vous. Le terminal a toujours un répertoire de travail courant.",
        objectif: "Affichez le répertoire dans lequel vous êtes.",
        indices: ["Il faut une commande qui affiche l'endroit où vous êtes.", "Elle a trois lettres et commence par p.", "pwd"],
        echec: "Lancez pwd et vérifiez que c'est bien votre dossier personnel.",
    },
    "orientation-02": {
        niveau: "Où suis-je ?",
        titre: "Faire le tour de la pièce",
        explication: "Lister d'abord, c'est voir ses options avant de choisir un chemin.",
        objectif: "Listez le contenu de votre dossier personnel.",
        echec: "La sortie ne montre pas encore le contenu attendu de votre dossier personnel.",
    },
    "orientation-03": {
        niveau: "Où suis-je ?",
        titre: "Savoir qui l'on est",
        explication: "Sur un poste comme sur un serveur, savoir sous quel utilisateur on travaille évite les mauvaises surprises de droits.",
        objectif: "Trouvez quel utilisateur exécute cette session.",
        indices: ["Cherchez une commande qui répond à la question « qui suis-je ? » (en anglais).", "C'est un seul mot, très parlant.", "whoami"],
        echec: "L'utilisateur de la session n'apparaît pas encore.",
    },
    "orientation-04": {
        niveau: "Où suis-je ?",
        titre: "Voir ce qui est caché",
        explication: "Les noms qui commencent par un point contiennent souvent de la configuration. Un ls simple ne les montre pas.",
        objectif: "Listez les fichiers cachés de votre dossier personnel, avec le format détaillé.",
        indices: ["ls accepte des options pour inclure les fichiers cachés et afficher les détails.", "Les deux options sont -a et -l ; on peut les combiner.", "ls -la"],
        echec: "Il manque les fichiers cachés ou les détails dans la sortie.",
    },

    "navigation-01": {
        niveau: "Se déplacer",
        titre: "Entrer dans projects",
        explication: "Un chemin relatif se lit à partir du répertoire courant.",
        objectif: "Entrez dans le répertoire projects.",
        echec: "Vous n'êtes pas encore dans projects.",
    },
    "navigation-02": {
        niveau: "Se déplacer",
        titre: "Revenir d'un cran",
        explication: "Le nom .. désigne le répertoire parent : l'un des raccourcis les plus utiles pour se déplacer vite.",
        objectif: "Revenez à votre dossier personnel depuis projects.",
        echec: "Le répertoire courant n'est pas encore votre dossier personnel.",
    },
    "navigation-03": {
        niveau: "Se déplacer",
        titre: "Rentrer à la maison",
        explication: "~ est un raccourci portable vers votre dossier personnel.",
        objectif: "Revenez à votre dossier personnel en utilisant ~.",
        echec: "~ ne vous a pas encore ramené chez vous.",
    },
    "navigation-04": {
        niveau: "Se déplacer",
        titre: "Visiter la racine",
        explication: "La barre oblique initiale représente la racine de tout le système de fichiers.",
        objectif: "Rendez-vous à la racine du système de fichiers virtuel.",
        echec: "Vous n'êtes pas encore à /.",
    },
    "navigation-05": {
        niveau: "Se déplacer",
        titre: "Rester sur place",
        explication: ". désigne le répertoire courant. C'est utile pour passer un chemin à d'autres commandes.",
        objectif: "Utilisez . sans changer d'endroit.",
        indices: ["Le point représente l'endroit où vous êtes.", "Vous pouvez le donner comme destination à cd.", "cd ."],
        echec: "Lancez cd . pour confirmer le répertoire courant.",
    },

    "build-01": {
        niveau: "Construire",
        titre: "Créer une pièce",
        explication: "Les répertoires sont des contenants. Créez-en un petit avant de le remplir.",
        objectif: "Dans sandbox, créez un répertoire nommé projects.",
        echec: "Le répertoire projects n'existe pas encore dans sandbox.",
    },
    "build-02": {
        niveau: "Construire",
        titre: "Tracer un chemin",
        explication: "mkdir -p évite de créer chaque répertoire intermédiaire un par un.",
        objectif: "Dans sandbox, créez le chemin src/components en une seule commande.",
        echec: "Le chemin imbriqué n'est pas encore complet.",
    },
    "build-03": {
        niveau: "Construire",
        titre: "Poser un repère",
        explication: "touch crée un fichier vide quand il n'existe pas encore.",
        objectif: "Dans sandbox, créez un fichier nommé README.md.",
        echec: "README.md n'existe pas encore dans sandbox.",
    },
    "build-04": {
        niveau: "Construire",
        titre: "Un petit journal",
        explication: "Combinez la création d'un répertoire et celle d'un fichier.",
        objectif: "Créez notes dans sandbox et placez-y le fichier today.txt.",
        echec: "notes ou today.txt manque dans sandbox.",
    },

    "move-copy-01": {
        niveau: "Déplacer et copier",
        titre: "Garder une copie",
        explication: "cp laisse l'original en place et crée une nouvelle entrée.",
        objectif: "Dans sandbox, copiez source.txt sous le nom source-copy.txt.",
        indices: ["Il faut une commande qui duplique sans supprimer la source.", "La forme générale est cp source destination.", "cp source.txt source-copy.txt"],
        echec: "La copie ou l'original n'est pas là où il devrait être.",
    },
    "move-copy-02": {
        niveau: "Déplacer et copier",
        titre: "Renommer un brouillon",
        explication: "mv sert à la fois à déplacer et à renommer.",
        objectif: "Dans sandbox, renommez draft.txt en final.txt.",
        echec: "L'ancien nom existe encore ou final.txt manque.",
    },
    "move-copy-03": {
        niveau: "Déplacer et copier",
        titre: "Dupliquer un dossier",
        explication: "Les répertoires demandent l'option récursive, car ils contiennent d'autres entrées.",
        objectif: "Copiez le dossier assets sous le nom assets-copy, avec son contenu.",
        indices: ["cp a besoin d'une option quand la source est un répertoire.", "L'option est -r.", "cp -r assets assets-copy"],
        echec: "Le dossier copié ou son contenu manque.",
    },
    "move-copy-04": {
        niveau: "Déplacer et copier",
        titre: "Déplacer l'ancien dossier",
        explication: "Déplacer un répertoire conserve son contenu tout en changeant son emplacement ou son nom.",
        objectif: "Renommez old-name en new-name.",
        echec: "Le répertoire n'a pas été renommé en gardant son contenu.",
    },

    "delete-01": {
        niveau: "Supprimer avec prudence",
        titre: "Supprimer un fichier",
        explication: "rm supprime directement : sous Unix, il n'y a pas de corbeille pour récupérer le fichier.",
        objectif: "Dans sandbox, supprimez old.txt.",
        echec: "old.txt existe encore.",
    },
    "delete-02": {
        niveau: "Supprimer avec prudence",
        titre: "D'abord vide",
        explication: "rmdir est volontairement prudent : il ne supprime que les répertoires vides.",
        objectif: "Supprimez le répertoire vide empty-folder.",
        echec: "empty-folder existe encore.",
    },
    "delete-03": {
        niveau: "Supprimer avec prudence",
        titre: "Raser une arborescence",
        explication: "rm -r parcourt un répertoire récursivement. Dans la vraie vie, relisez le chemin deux fois.",
        objectif: "Supprimez le dossier build et tout son contenu.",
        indices: ["rm seul ne supprime pas les répertoires.", "Il faut l'option récursive.", "rm -r build"],
        echec: "build ou une partie de son contenu existe encore.",
    },

    "read-01": {
        niveau: "Lire des fichiers",
        titre: "Lire le message d'accueil",
        explication: "cat est l'outil direct pour afficher un fichier en entier.",
        objectif: "Lisez welcome.txt et trouvez le message d'accueil.",
        echec: "La sortie ne contient pas encore le message d'accueil.",
    },
    "read-02": {
        niveau: "Lire des fichiers",
        titre: "Regarder le début",
        explication: "head est utile quand seul le début d'un journal ou d'un gros fichier vous intéresse.",
        objectif: "Affichez les deux premières lignes de server.log.",
        echec: "La sortie ne montre pas exactement les deux premières lignes de server.log.",
    },
    "read-03": {
        niveau: "Lire des fichiers",
        titre: "Regarder la fin",
        explication: "tail montre la partie la plus récente d'un fichier sans tout afficher.",
        objectif: "Affichez les deux dernières lignes de server.log.",
        echec: "La sortie ne montre pas exactement les deux dernières lignes de server.log.",
    },
    "read-04": {
        niveau: "Lire des fichiers",
        titre: "Ouvrir les notes",
        explication: "less est entre cat et un outil de recherche : il permet d'inspecter sans inonder l'écran.",
        objectif: "Inspectez le README du dossier projects.",
        echec: "Le contenu du README de projects n'apparaît pas encore.",
    },

    "search-01": {
        niveau: "Chercher",
        titre: "Trouver une erreur",
        explication: "grep travaille sur le contenu : il indique quelles lignes contiennent un mot ou un motif.",
        objectif: "Trouvez les lignes qui contiennent ERROR dans server.log.",
        echec: "Les lignes ERROR de server.log n'apparaissent pas encore.",
    },
    "search-02": {
        niveau: "Chercher",
        titre: "Ignorer la casse",
        explication: "-i empêche les différences de majuscules et minuscules de cacher un résultat.",
        objectif: "Trouvez WARNING alors que le fichier l'écrit avec une autre casse.",
        echec: "La recherche n'a pas encore trouvé Warning en ignorant la casse.",
    },
    "search-03": {
        niveau: "Chercher partout",
        titre: "Fouiller le projet",
        explication: "Avec -r, grep parcourt les dossiers et indique de quel fichier vient chaque résultat.",
        objectif: "Trouvez la ligne TODO dans n'importe quel fichier de projects.",
        echec: "La ligne TODO et son fichier n'apparaissent pas encore.",
    },
    "search-04": {
        niveau: "Chercher par nom",
        titre: "Repérer les journaux",
        explication: "find cherche des chemins et des noms : pas besoin de connaître le contenu à l'avance.",
        objectif: "Trouvez tous les fichiers .log de votre dossier personnel.",
        echec: "Tous les fichiers .log n'apparaissent pas encore.",
    },
    "search-05": {
        niveau: "Chercher par type",
        titre: "Séparer fichiers et dossiers",
        explication: "find peut aussi filtrer le type d'entrée, utile quand un nom se répète.",
        objectif: "Trouvez les fichiers .txt de projects sans renvoyer de répertoires.",
        echec: "La sortie ne contient pas exactement les fichiers .txt attendus (sans répertoire).",
    },

    "redirect-01": {
        niveau: "Rediriger",
        titre: "Écrire un fichier",
        explication: "> envoie la sortie d'une commande dans un fichier et remplace son contenu.",
        objectif: "Créez hello.txt avec une seule ligne : hello.",
        indices: ["Utilisez echo pour produire une ligne et un opérateur pour l'enregistrer.", "L'opérateur qui remplace est >.", "echo \"hello\" > hello.txt"],
        echec: "hello.txt ne contient pas exactement la ligne attendue.",
    },
    "redirect-02": {
        niveau: "Rediriger",
        titre: "Ajouter une deuxième ligne",
        explication: ">> ajoute à la fin : une petite différence aux grandes conséquences dans les journaux.",
        objectif: "Ajoutez la ligne world à hello.txt sans effacer hello.",
        indices: ["Il faut écrire sans remplacer ce qui est déjà là.", "L'opérateur a deux signes >.", "echo \"world\" >> hello.txt"],
        echec: "Le fichier ne garde pas hello ou ne se termine pas par world.",
    },
    "redirect-03": {
        niveau: "Rediriger",
        titre: "Conserver le signal",
        explication: "Combiner une recherche et une redirection transforme une sortie éphémère en fichier utile.",
        objectif: "Enregistrez toutes les lignes ERROR de server.log dans errors.txt.",
        echec: "errors.txt ne contient pas encore les deux lignes ERROR.",
    },

    "pipes-01": {
        niveau: "Tubes",
        titre: "Filtrer un flux",
        explication: "Un tube transforme la sortie de la commande de gauche en entrée de la commande de droite.",
        objectif: "Affichez seulement les lignes de users.txt qui contiennent admin.",
        echec: "La sortie ne montre pas seulement les lignes admin.",
    },
    "pipes-02": {
        niveau: "Tubes",
        titre: "Filtrer une liste",
        explication: "Les noms listés sont aussi du texte : ls peut alimenter un autre outil.",
        objectif: "Listez seulement les fichiers .txt de votre dossier personnel.",
        echec: "La sortie ne montre pas seulement les fichiers .txt.",
    },
    "pipes-03": {
        niveau: "Tubes",
        titre: "Trier et dédoublonner",
        explication: "Les tubes permettent de fabriquer de petits outils en enchaînant des transformations.",
        objectif: "Triez names.txt et supprimez les doublons consécutifs.",
        indices: ["Il faut deux opérations : l'une trie, l'autre fusionne les répétitions.", "Reliez-les avec |.", "sort names.txt | uniq"],
        echec: "Le résultat n'est pas trié et dédoublonné.",
    },

    "combine-01": {
        niveau: "Combiner",
        titre: "Boss 1 · Mise en place d'un projet",
        explication: "Plus de recette pas à pas : pensez à la structure finale et construisez-la avec ce que vous savez déjà.",
        objectif: "Dans ~/projects, créez website avec index.html, styles.css et scripts/app.js.",
        indices: ["Travaillez d'abord dans ~/projects.", "mkdir -p peut construire website/scripts.", "mkdir -p ~/projects/website/scripts puis touch sur les trois fichiers"],
        echec: "La structure de website n'est pas encore complète.",
    },
    "combine-02": {
        niveau: "Combiner",
        titre: "Vérifier la structure",
        explication: "Une fois la structure créée, find est un moyen reproductible de la vérifier.",
        objectif: "Affichez les trois fichiers de projects/website.",
        echec: "Les trois fichiers de projects/website n'apparaissent pas encore.",
    },
    "combine-03": {
        niveau: "Combiner",
        titre: "Extraire le signal",
        explication: "Chercher puis rediriger : l'une des combinaisons les plus courantes quand on enquête sur un incident.",
        objectif: "Trouvez les lignes d'erreur, quelle que soit la casse, et enregistrez-les dans errors.txt.",
        indices: ["La recherche doit ignorer la casse et écrire dans un fichier.", "Combinez grep -i et >.", "grep -i error app.log > errors.txt"],
        echec: "errors.txt ne contient pas les deux lignes d'erreur.",
    },
    "combine-04": {
        niveau: "Combiner",
        titre: "Emballer le travail",
        explication: "Une archive permet de déplacer un ensemble de fichiers sans perdre sa structure.",
        objectif: "Créez website.tar à partir du dossier website, puis affichez son contenu.",
        indices: ["tar crée une archive à partir d'un chemin.", "-c pour créer, -f pour la nommer, -t pour la lister.", "tar -cf website.tar website"],
        echec: "L'archive website.tar ou la liste de son contenu manque.",
    },

    "permissions-01": {
        niveau: "Droits",
        titre: "Rendre exécutable",
        explication: "x signifie qu'un fichier peut être exécuté. Pour un script, c'est souvent le premier droit à ajouter.",
        objectif: "Ajoutez le droit d'exécution à script.sh.",
        indices: ["La commande qui change les droits est chmod.", "Utilisez le mode symbolique +x.", "chmod +x script.sh"],
        echec: "script.sh n'a pas encore le droit x.",
    },
    "permissions-02": {
        niveau: "Droits",
        titre: "Lire 755",
        explication: "La notation numérique additionne r=4, w=2 et x=1 pour le propriétaire, le groupe et les autres.",
        objectif: "Donnez à deploy.sh le mode 755.",
        indices: ["Trois chiffres : propriétaire, groupe, autres.", "7 vaut rwx ; 5 vaut r-x.", "chmod 755 deploy.sh"],
        echec: "Le mode final de deploy.sh n'est pas 755.",
    },
    "permissions-03": {
        niveau: "Droits",
        titre: "Lire le mode",
        explication: "ls -l permet d'inspecter un fichier avant de l'exécuter ou de le partager.",
        objectif: "Affichez les droits détaillés de script.sh et vérifiez qu'il est exécutable.",
        echec: "Les droits détaillés de script.sh (-rwxr-xr-x) n'apparaissent pas encore.",
    },

    "process-01": {
        niveau: "Processus",
        titre: "Prendre un instantané",
        explication: "ps est un instantané : inutile de fermer quoi que ce soit pour voir ce qui tourne.",
        objectif: "Listez les processus simulés avec leurs détails.",
        echec: "La table des processus n'apparaît pas dans le format attendu.",
    },
    "process-02": {
        niveau: "Processus",
        titre: "Surveiller l'activité",
        explication: "top présente les processus selon les ressources qu'ils consomment.",
        objectif: "Affichez un instantané des processus les plus gourmands.",
        echec: "La vue de top n'apparaît pas encore.",
    },
    "process-03": {
        niveau: "Processus",
        titre: "Arrêter un processus",
        explication: "kill prend un PID, pas un nom. Vérifiez le numéro avant de l'utiliser.",
        objectif: "Arrêtez le processus fictif hestim-planner, de PID 840.",
        echec: "Le processus 840 tourne encore.",
    },
    "process-04": {
        niveau: "Processus",
        titre: "Arrêter par nom",
        explication: "killall agit sur un nom et peut toucher plusieurs processus à la fois.",
        objectif: "Arrêtez tous les processus fictifs dont la commande contient node.",
        echec: "Un processus node tourne encore.",
    },

    "system-01": {
        niveau: "Système",
        titre: "Nommer le système",
        explication: "Linux et macOS partagent beaucoup d'outils, mais n'affichent pas toujours exactement la même chose.",
        objectif: "Identifiez le système d'exploitation simulé de cette session.",
        echec: "La session devrait s'identifier comme Linux.",
    },
    "system-02": {
        niveau: "Système",
        titre: "Vérifier le disque",
        explication: "df indique l'espace encore libre sur les systèmes de fichiers montés.",
        objectif: "Vérifiez l'espace disponible dans le système de fichiers virtuel.",
        echec: "Le tableau de df n'est pas complet.",
    },
    "system-03": {
        niveau: "Système",
        titre: "Mesurer un projet",
        explication: "du mesure l'espace occupé par un chemin ; -s résume et -h rend le résultat lisible.",
        objectif: "Mesurez la taille du dossier projects.",
        echec: "La sortie de du ne donne pas de mesure pour projects.",
    },
    "system-04": {
        niveau: "Système",
        titre: "Lire l'horloge",
        explication: "uptime résume le temps de fonctionnement et la charge : un premier coup d'œil rapide sur un serveur.",
        objectif: "Vérifiez depuis combien de temps la machine virtuelle tourne.",
        echec: "La sortie ne contient pas le résumé d'uptime.",
    },
    "system-05": {
        niveau: "Système",
        titre: "La mémoire sous Linux",
        explication: "free est courant sous Linux mais n'existe pas en standard sur macOS. La différence compte quand on change de machine.",
        objectif: "Dans cette session Linux, vérifiez la mémoire disponible.",
        echec: "La sortie de free ne montre pas le tableau de la mémoire.",
    },

    "network-01": {
        niveau: "Réseau",
        titre: "Tester la joignabilité",
        explication: "ping donne un premier signal de connectivité ; il ne prouve pas qu'une application web fonctionne.",
        objectif: "Envoyez trois pings simulés à raspberrypi.",
        indices: ["ping prend un hôte et peut limiter le nombre de paquets.", "Mettez -c 3 avant le nom de l'hôte.", "ping -c 3 raspberrypi"],
        echec: "Les statistiques de ping ne montrent pas trois paquets sans perte.",
    },
    "network-02": {
        niveau: "Réseau",
        titre: "Interroger un service",
        explication: "curl est souvent l'outil le plus rapide pour dialoguer en HTTP depuis le terminal.",
        objectif: "Interrogez avec curl le point de santé simulé (https://example.com/health).",
        echec: "La réponse simulée de curl n'apparaît pas.",
    },
    "network-03": {
        niveau: "Réseau",
        titre: "Ouvrir le dossier",
        explication: "xdg-open . ouvre un dossier dans le bureau Linux ; macOS utilise open . à la place.",
        objectif: "Ouvrez le répertoire courant avec l'outil du bureau Linux.",
        echec: "xdg-open n'a pas renvoyé la confirmation simulée.",
    },

    "remote-01": {
        niveau: "À distance",
        titre: "Boss 4 · Raspberry Pi",
        explication: "Une connexion à distance change le contexte : l'invite et le système de fichiers ne sont plus ceux de votre machine.",
        objectif: "Connectez-vous au Raspberry Pi simulé (utilisateur learner) et entrez dans /var/log.",
        echec: "Vous n'êtes pas encore connecté au Raspberry Pi, dans /var/log.",
    },
    "remote-02": {
        niveau: "À distance",
        titre: "Envoyer un rapport",
        explication: "scp copie des fichiers sans ouvrir un second terminal interactif.",
        objectif: "Copiez report.txt de votre session locale vers le dossier personnel de learner sur raspberrypi.",
        echec: "report.txt n'apparaît pas encore dans le dossier personnel distant.",
    },
    "remote-03": {
        niveau: "À distance",
        titre: "Lire le journal distant",
        explication: "Se connecter, inspecter, repartir : une session SSH n'est qu'une suite de contextes, pas de la magie.",
        objectif: "Connectez-vous à raspberrypi (utilisateur learner) et lisez server.log dans /var/log.",
        echec: "La session ne s'est pas terminée par l'affichage du journal distant et de ses erreurs.",
    },

    "environment-01": {
        niveau: "Environnement",
        titre: "Trouver sa maison",
        explication: "HOME est une variable d'environnement : l'utiliser rend un chemin plus portable qu'un nom écrit en dur.",
        objectif: "Affichez la valeur de HOME.",
        echec: "HOME ne s'est pas affiché comme votre dossier personnel.",
    },
    "environment-02": {
        niveau: "Environnement",
        titre: "Nommer son projet",
        explication: "export rend une variable disponible pour les commandes suivantes de la session.",
        objectif: "Donnez à PROJECT la valeur terminal-quest et vérifiez-la.",
        indices: ["Une variable s'affecte avec NOM=valeur.", "export garde l'affectation disponible pour la session.", "export PROJECT=terminal-quest"],
        echec: "PROJECT n'a pas la bonne valeur.",
    },
    "environment-03": {
        niveau: "Environnement",
        titre: "Enquêter sur ses outils",
        explication: "man, which et history vous aident à continuer quand la mémoire flanche.",
        objectif: "Consultez l'aide de grep, localisez la commande, puis relisez votre historique.",
        indices: ["Inutile de deviner : man explique et which localise.", "Après les deux, history montre ce que vous avez fait.", "man grep, which grep, puis history"],
        echec: "Il manque encore un ou plusieurs des trois outils d'enquête.",
    },

    "power-01": {
        niveau: "Utilisateur avancé",
        titre: "Boss 2 · Le fichier perdu",
        explication: "Quand on connaît le nom mais pas l'emplacement : d'abord le trouver, ensuite le déplacer.",
        objectif: "Trouvez config.json dans projects et déplacez-le dans ~/backup.",
        indices: ["Vérifiez que la destination existe avant de déplacer.", "find révèle le chemin ; mv change l'emplacement.", "mkdir -p ~/backup puis mv ~/projects/app/config.json ~/backup/config.json"],
        echec: "config.json n'a pas encore été déplacé dans ~/backup.",
    },
    "power-02": {
        niveau: "Utilisateur avancé",
        titre: "Boss 3 · Les journaux",
        explication: "Une opération courante lors d'un incident : filtrer un signal et le conserver.",
        objectif: "Trouvez toutes les lignes contenant ERROR dans server.log et enregistrez-les dans errors.txt.",
        indices: ["grep sélectionne des lignes et > les enregistre.", "Le motif est ERROR et le fichier de sortie errors.txt.", "grep ERROR server.log > errors.txt"],
        echec: "errors.txt ne contient pas exactement les lignes ERROR attendues.",
    },
    "power-03": {
        niveau: "Utilisateur avancé",
        titre: "Un rapport propre",
        explication: "Enchaînez recherche récursive, tri, dédoublonnage et redirection pour produire un rapport.",
        objectif: "Trouvez les lignes admin dans projects/logs, triez-les, supprimez les doublons et enregistrez-les dans admin-users.txt.",
        indices: ["Commencez par un grep récursif, puis transformez la sortie en liste stable.", "sort et uniq vont dans un tube, avant la redirection.", "grep -r admin projects/logs | sort | uniq > admin-users.txt"],
        echec: "admin-users.txt n'existe pas ou ne contient pas les lignes admin uniques attendues.",
    },

    "server-01": {
        niveau: "Mission serveur",
        titre: "Entrer dans la salle des serveurs",
        explication: "La mission finale réunit connexion distante, journaux, espace disque et processus, comme une petite astreinte.",
        objectif: "Connectez-vous à server (utilisateur admin), enregistrez les erreurs de /var/log dans ~/errors.txt, vérifiez l'espace disque et arrêtez le processus node trop gourmand.",
        indices: ["Changez d'abord de machine avec ssh, puis travaillez sur /var/log.", "grep -r et > créent le rapport en une seule commande.", "ssh admin@server, puis grep -r ERROR /var/log > ~/errors.txt, df -h, ps aux et kill 2451."],
        echec: "Il manque encore la connexion, le rapport d'erreurs ou l'arrêt du processus.",
    },
    "server-02": {
        niveau: "Mission serveur",
        titre: "Récupérer une archive",
        explication: "Compresser, transférer et restaurer des fichiers : le quotidien de l'administration d'une machine.",
        objectif: "Créez backup.zip avec release.txt, extrayez-le dans restored, puis compressez l'original avec gzip.",
        indices: ["zip et unzip manipulent une archive .zip ; gzip remplace l'original par un fichier .gz.", "unzip -d restored choisit la destination.", "zip backup.zip release.txt ; unzip backup.zip -d restored ; gzip release.txt"],
        echec: "Il manque le zip, la copie restaurée ou le fichier .gz final.",
    },
    "server-03": {
        niveau: "Mission serveur",
        titre: "Tenir son propre manuel",
        explication: "Être à l'aise, c'est aussi savoir chercher : inutile de mémoriser ce qu'on retrouve vite.",
        objectif: "Utilisez man, which et history pour enquêter sur find et garder la trace de votre démarche.",
        echec: "La séquence d'enquête n'est pas encore complète.",
    },
};
